package view;

public enum MenuCommand {
    EXIT, LOGIN_USER, LOGOUT_USER, REGISTER_USER, ADD_USER, VIEW_USER, EDIT_USER, DELETE_USER, LIST_ALL_USERS,
    ADD_QUIZ, VIEW_QUIZ, EDIT_QUIZ, DELETE_QUIZ, LIST_ALL_QUIZZES,
    ADD_QUESTION, VIEW_QUESTION, EDIT_QUESTION, DELETE_QUESTION,
    ADD_ANSWER, VIEW_ANSWER, EDIT_ANSWER, DELETE_ANSWER,
    PLAY_QUIZ, LIST_ALL_QUIZ_RESULTS
}
